apiVersion: apps/v1
kind: Deployment
metadata:
  name: mpsc-portal-deployment
  labels:
    app: mpsc-portal
spec:
  replicas: 2 # 1GB रॅमसाठी २ पॉड्स सुरक्षित आणि लोड-बॅलेंस्ड चालतील
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mpsc-portal
  template:
    metadata:
      labels:
        app: mpsc-portal
    spec:
      containers:
      - name: mpsc-portal
        image: mpsc-portal:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
